"""
youtube_pw_downloader.py

Playwright를 사용하여 YouTube 쿠키를 실시간으로 추출하는 헬퍼 모듈.
봇 감지 우회를 위해 headless Chromium 브라우저를 실행하고
Netscape 형식의 cookies.txt를 생성합니다.

[중요] FastAPI는 asyncio 이벤트 루프 위에서 동작합니다.
playwright.sync_api는 asyncio 루프 내부에서 직접 호출할 수 없으므로
ThreadPoolExecutor를 사용해 별도 스레드에서 실행합니다.

캐시 TTL: 30분 (매 요청마다 브라우저를 실행하지 않도록 최적화)
"""

import os
import time
import logging
import tempfile
import concurrent.futures
from pathlib import Path
from typing import Optional

logger = logging.getLogger("youtube_pw_downloader")

# 쿠키 캐시 설정
_COOKIE_CACHE_TTL = 30 * 60  # 30분 (초 단위)
_cached_cookie_path: Optional[str] = None
_cached_cookie_time: float = 0.0

# Playwright 브라우저 실행용 단일 스레드 Executor
# asyncio 루프와 분리된 전용 스레드에서 Playwright를 실행합니다.
_thread_executor = concurrent.futures.ThreadPoolExecutor(max_workers=1, thread_name_prefix="playwright")


def _is_cache_valid() -> bool:
    """캐시된 쿠키 파일이 유효한지 확인합니다."""
    global _cached_cookie_path, _cached_cookie_time
    if not _cached_cookie_path:
        return False
    if not os.path.exists(_cached_cookie_path):
        return False
    if time.time() - _cached_cookie_time > _COOKIE_CACHE_TTL:
        return False
    if os.path.getsize(_cached_cookie_path) < 100:
        return False
    return True


def _cookies_to_netscape(cookies: list) -> str:
    """
    Playwright 쿠키 딕셔너리 목록을 Netscape cookies.txt 포맷으로 변환합니다.
    yt-dlp는 Netscape 포맷을 사용합니다.
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by Playwright YouTube Downloader", ""]
    for c in cookies:
        domain = c.get("domain", "")
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expires = int(c.get("expires", 0))
        if expires < 0:
            expires = 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)


def _sync_extract_cookies(out_path: str) -> Optional[str]:
    """
    실제 Playwright 브라우저 실행 로직 (동기).
    이 함수는 반드시 asyncio 이벤트 루프 밖의 스레드에서 호출해야 합니다.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.error("[Playwright] playwright가 설치되어 있지 않습니다.")
        return None

    logger.info("[Playwright] headless Chromium 실행 중... YouTube 쿠키 추출 시작")

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-setuid-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                    "--disable-background-networking",
                    "--disable-default-apps",
                    "--disable-extensions",
                    "--disable-sync",
                    "--disable-translate",
                    "--hide-scrollbars",
                    "--metrics-recording-only",
                    "--mute-audio",
                    "--no-first-run",
                    "--safebrowsing-disable-auto-update",
                    "--ignore-certificate-errors",
                ]
            )

            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                locale="ko-KR",
                timezone_id="Asia/Seoul",
            )

            page = context.new_page()

            logger.info("[Playwright] https://www.youtube.com 접속 중...")
            page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)

            # 쿠키 동의 팝업 처리
            try:
                accept_btn = page.locator(
                    "button:has-text('Accept all'), button:has-text('모두 동의'), button:has-text('동의')"
                ).first
                if accept_btn.is_visible(timeout=3000):
                    accept_btn.click()
                    page.wait_for_timeout(1000)
            except Exception:
                pass

            page.wait_for_timeout(2000)

            cookies = context.cookies()
            logger.info(f"[Playwright] {len(cookies)}개 쿠키 추출 완료")
            browser.close()

        if not cookies:
            logger.warning("[Playwright] 쿠키가 비어있습니다.")
            return None

        netscape_content = _cookies_to_netscape(cookies)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(netscape_content)

        logger.info(f"[Playwright] 쿠키 파일 저장 완료: {out_path} ({os.path.getsize(out_path)} bytes)")
        return out_path

    except Exception as e:
        logger.error(f"[Playwright] 쿠키 추출 실패 (내부): {e}")
        return None


def extract_youtube_cookies_via_playwright(out_path: Optional[str] = None) -> Optional[str]:
    """
    YouTube 쿠키를 추출합니다. asyncio 루프 내부에서도 안전하게 호출 가능합니다.

    내부적으로 ThreadPoolExecutor를 사용해 Playwright sync API를
    별도 스레드에서 실행하므로 FastAPI/asyncio 환경과 충돌하지 않습니다.

    Returns:
        성공 시 쿠키 파일 경로(str), 실패 시 None.
    """
    global _cached_cookie_path, _cached_cookie_time

    # 캐시가 유효하면 즉시 반환
    if _is_cache_valid():
        remaining = int(_COOKIE_CACHE_TTL - (time.time() - _cached_cookie_time))
        logger.info(f"[Playwright] 캐시된 쿠키 사용 중 (남은 TTL: {remaining}초)")
        return _cached_cookie_path

    if out_path is None:
        cache_dir = Path(tempfile.gettempdir()) / "gemini_fancam_playwright"
        cache_dir.mkdir(exist_ok=True)
        out_path = str(cache_dir / "yt_cookies.txt")

    try:
        # ThreadPoolExecutor에서 실행 → asyncio 루프와 완전히 분리된 스레드
        future = _thread_executor.submit(_sync_extract_cookies, out_path)
        result = future.result(timeout=60)  # 최대 60초 대기
    except concurrent.futures.TimeoutError:
        logger.error("[Playwright] 쿠키 추출 시간 초과 (60초)")
        return None
    except Exception as e:
        logger.error(f"[Playwright] 쿠키 추출 실패: {e}")
        return None

    if result and os.path.exists(result):
        _cached_cookie_path = result
        _cached_cookie_time = time.time()

    return result


def clear_cookie_cache():
    """캐시된 쿠키를 초기화합니다. (강제 갱신 시 사용)"""
    global _cached_cookie_path, _cached_cookie_time
    _cached_cookie_path = None
    _cached_cookie_time = 0.0
    logger.info("[Playwright] 쿠키 캐시가 초기화되었습니다.")
