import os
import pickle
import logging
import json
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from googleapiclient.errors import HttpError

# 구글 API 스코프 설정 (동영상 업로드 권한)
SCOPES = ['https://www.googleapis.com/auth/youtube.upload']

# 로깅 설정
logger = logging.getLogger("youtube_uploader")

class YouTubeUploader:
    def __init__(self, client_secrets_file='credentials.json', token_file='token.pickle'):
        logger.info("YouTubeUploader 초기화 중...")
        self.client_secrets_file = client_secrets_file
        self.token_file = token_file
        self.youtube = self._get_authenticated_service()

    def _get_authenticated_service(self):
        creds = None
        # 이전에 저장된 토큰이 있는지 확인
        if os.path.exists(self.token_file):
            logger.info(f"기존 토큰 파일을 로드합니다: {self.token_file}")
            with open(self.token_file, 'rb') as token:
                creds = pickle.load(token)
        
        # 유효한 인증 정보가 없으면 로그인 진행
        if not creds or not creds.valid:
            if creds and creds.expired and creds.refresh_token:
                logger.info("토큰이 만료되어 갱신을 시도합니다.")
                creds.refresh(Request())
            else:
                logger.info("새로운 OAuth 인증 흐름을 시작합니다.")
                if not os.path.exists(self.client_secrets_file):
                    logger.error(f"클라이언트 비밀 파일이 없습니다: {self.client_secrets_file}")
                    raise FileNotFoundError(
                        f"'{self.client_secrets_file}' 파일이 없습니다. "
                        "Google Cloud Console에서 OAuth 2.0 클라이언트 ID JSON을 다운로드하여 저장해주세요."
                    )
                flow = InstalledAppFlow.from_client_secrets_file(self.client_secrets_file, SCOPES)
                creds = flow.run_local_server(port=0)
            
            # 다음을 위해 인증 정보 저장
            with open(self.token_file, 'wb') as token:
                logger.info(f"갱신된 토큰을 저장합니다: {self.token_file}")
                pickle.dump(creds, token)

        logger.info("유튜브 서비스 인증 성공")
        return build('youtube', 'v3', credentials=creds)

    def upload_video(self, file_path, title, description, category_id='22', privacy_status='public'):
        """
        영상을 유튜브에 업로드합니다.
         Shorts로 인식되게 하려면 제목이나 설명에 #Shorts 를 포함하는 것이 좋습니다.
        """
        if not os.path.exists(file_path):
            logger.error(f"업로드할 파일을 찾을 수 없습니다: {file_path}")
            raise FileNotFoundError(f"파일을 찾을 수 없습니다: {file_path}")

        logger.info(f"유튜브 업로드 요청 시작: [{title}] 파일: {file_path}")
        body = {
            'snippet': {
                'title': title,
                'description': description,
                'categoryId': category_id
            },
            'status': {
                'privacyStatus': privacy_status,
                'selfDeclaredMadeForKids': False
            }
        }

        # 미디어 파일 설정
        media = MediaFileUpload(
            file_path, 
            mimetype='video/mp4', 
            chunksize=-1, 
            resumable=True
        )

        request = self.youtube.videos().insert(
            part='snippet,status',
            body=body,
            media_body=media
        )

        logger.info("업로드 청크 전송 중...")
        response = None
        try:
            while response is None:
                status, response = request.next_chunk()
                if status:
                    logger.debug(f"업로드 진행률: {int(status.progress() * 100)}%")
        except HttpError as e:
            error_details = e.content.decode('utf-8')
            if "youtubeSignupRequired" in error_details:
                logger.error("유튜브 채널이 없는 계정입니다. 채널을 먼저 생성해야 합니다.")
                raise Exception(
                    "유튜브 채널이 활성화되지 않은 구글 계정입니다. "
                    "해당 계정으로 유튜브(youtube.com)에 접속하여 '채널 만들기'를 완료한 후 다시 시도해주세요."
                )
            logger.error(f"HTTP 에러 발생: {e}")
            raise e

        video_id = response.get('id')
        logger.info(f"유튜브 업로드 완료! 비디오 ID: {video_id}")
        return video_id

if __name__ == '__main__':
    # 간단한 CLI 테스트용
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--file', required=True, help='Path to the video file')
    parser.add_argument('--title', default='Gemini Shorts Test', help='Video title')
    parser.add_argument('--desc', default='Generated by Gemini Fancam #Shorts', help='Video description')
    args = parser.parse_args()

    try:
        uploader = YouTubeUploader()
        uploader.upload_video(args.file, args.title, args.desc)
    except Exception as e:
        print(f"에러 발생: {e}")
